spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/hz?useUnicode=true&characterEncoding=utf8
        username: root       # 数据库用户名
        password: password   # 数据库密码
        driver-class-name: com.mysql.jdbc.Driver

        tomcat:
            max-wait: 10000
            max-active: 50000
            test-on-borrow: true
    jpa:
        database: MYSQL
        hibernate.ddl-auto: update
        show-sql: true
        generate-ddl: true

    http:
      multipart:
        max-file-size: 2048MB
        max-request-size: 2048MB

server:
    port: 2006

logging:
  level:
    org:
      springframework:
        web: DEBUG
